"""follower_node — deterministic 20 Hz offboard controller + gimbal servo.

Design: docs/drone_follow_design.md §5 (control law) and §6 (state machine).
Milestones 4-6.

HARD RULE: the 20 Hz timer publishes OffboardControlMode + TrajectorySetpoint
on EVERY tick, in EVERY state (including SEARCH/REACQUIRE/HOLD), or PX4 drops
offboard mode. Nothing in this node may block on perception.

FRAMES — be paranoid here:
  * PX4 (/fmu/...) is NED, body frame FRD. ROS convention is ENU/FLU.
  * TargetState.position_cam is CAMERA OPTICAL (x right, y down, z forward).
  * Gimbal joint commands (via ros_gz bridge) are ABSOLUTE angles in radians
    in the gz model (FLU) frame: pitch + = camera down (limits -1.57..+0.5),
    yaw + = camera left (limits -1.57..+1.57). See setup_gimbal.py.
  * NED yaw/yawspeed: positive = clockwise viewed from above (turn right);
    FLU yaw positive = counter-clockwise (turn left). Opposite signs!
Every conversion below is commented at the boundary.
"""

import math

import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import (QoSDurabilityPolicy, QoSHistoryPolicy, QoSProfile,
                       QoSReliabilityPolicy)
from sensor_msgs.msg import CameraInfo
from std_msgs.msg import Float64

from px4_msgs.msg import (OffboardControlMode, TrajectorySetpoint,
                          VehicleCommand, VehicleOdometry)
from drone_follow_msgs.msg import TargetState

from .geometry import frd_to_ned, optical_to_frd, yaw_from_quat
from .pid import PID, clamp

# Gimbal joint limits from setup_gimbal.py (SDF is generated by that script).
GIMBAL_PITCH_MIN, GIMBAL_PITCH_MAX = -1.57, 1.57  # rad, + = camera down
GIMBAL_YAW_MIN, GIMBAL_YAW_MAX = -1.57, 1.57      # rad, + = camera left

DT = 0.05  # 20 Hz — the offboard heartbeat rate. Do not lower.


class FollowerNode(Node):

    def __init__(self):
        super().__init__('follower_node')

        # ---- parameters (ALL control values UNTUNED — need sim tuning) ----
        self.declare_parameter('standoff_m', 8.0)        # UNTUNED default — needs sim tuning
        self.declare_parameter('alt_hold_m', 6.0)        # UNTUNED default — needs sim tuning
        self.declare_parameter('v_max', 4.0)             # UNTUNED default — needs sim tuning
        self.declare_parameter('yaw_rate_max', 0.8)      # UNTUNED default — needs sim tuning
        self.declare_parameter('kp_standoff', 0.5)       # UNTUNED default — needs sim tuning
        self.declare_parameter('kp_lateral', 1.0)        # UNTUNED default — needs sim tuning
        self.declare_parameter('kp_alt', 0.7)            # UNTUNED default — needs sim tuning
        self.declare_parameter('k_body_yaw', 0.6)        # UNTUNED default — needs sim tuning
        self.declare_parameter('kp_gimbal_pitch', 0.6)   # UNTUNED default — needs sim tuning
        self.declare_parameter('kp_gimbal_yaw', 0.6)     # UNTUNED default — needs sim tuning
        self.declare_parameter('vel_ff_alpha', 0.2)      # EMA weight; UNTUNED default — needs sim tuning
        self.declare_parameter('lost_frames_to_reacquire', 10)  # UNTUNED default — needs sim tuning
        self.declare_parameter('reacquire_timeout_s', 8.0)      # UNTUNED default — needs sim tuning
        self.declare_parameter('search_yaw_amplitude', 1.0)     # rad; UNTUNED default — needs sim tuning
        self.declare_parameter('search_yaw_period_s', 12.0)     # UNTUNED default — needs sim tuning
        self.declare_parameter('search_pitch', 0.7854)  # rad, + = down; UNTUNED default — needs sim tuning
        # Convenience for SITL testing: stream setpoints, then switch to
        # offboard + arm via VehicleCommand (like px4_ros_com offboard example).
        self.declare_parameter('auto_arm', False)

        gp = self.get_parameter
        self.d_star = float(gp('standoff_m').value)
        self.alt_hold = float(gp('alt_hold_m').value)
        self.v_max = float(gp('v_max').value)
        self.wr_max = float(gp('yaw_rate_max').value)
        self.k_body_yaw = float(gp('k_body_yaw').value)
        self.kp_gp = float(gp('kp_gimbal_pitch').value)
        self.kp_gy = float(gp('kp_gimbal_yaw').value)
        self.ff_alpha = float(gp('vel_ff_alpha').value)
        self.lost_thresh = int(gp('lost_frames_to_reacquire').value)
        self.reacq_timeout = float(gp('reacquire_timeout_s').value)
        self.search_amp = float(gp('search_yaw_amplitude').value)
        self.search_period = float(gp('search_yaw_period_s').value)
        self.search_pitch = float(gp('search_pitch').value)
        self.auto_arm = bool(gp('auto_arm').value)

        self.pid_d = PID(float(gp('kp_standoff').value),
                         out_min=-self.v_max, out_max=self.v_max)
        self.pid_lat = PID(float(gp('kp_lateral').value),
                           out_min=-self.v_max / 2, out_max=self.v_max / 2)
        self.pid_alt = PID(float(gp('kp_alt').value),
                           out_min=-2.0, out_max=2.0)  # UNTUNED climb-rate limit

        # ---- state ----
        self.state = 'SEARCH'
        self.tgt: TargetState | None = None
        self.lost = 0                 # consecutive not-visible TargetState msgs
        self.reacq_started = None     # sim-time seconds when REACQUIRE entered
        self.odom: VehicleOdometry | None = None
        self.cam_w = self.cam_h = None
        self.cam_cx = self.cam_cy = None
        self.gimbal_pitch = self.search_pitch
        self.gimbal_yaw = 0.0
        self.t = 0.0                  # local timer clock for the search sweep
        self.tick = 0
        self.tgt_pos_ned = None       # last target position, world NED
        self.tgt_vel_ned = np.zeros(3)  # EMA target velocity, world NED
        self.tgt_pos_t = None

        # ---- I/O ----
        # PX4 uXRCE publishers/subscribers are BestEffort; a Reliable
        # subscription to /fmu/out/* receives nothing.
        px4_qos = QoSProfile(
            reliability=QoSReliabilityPolicy.BEST_EFFORT,
            durability=QoSDurabilityPolicy.TRANSIENT_LOCAL,
            history=QoSHistoryPolicy.KEEP_LAST, depth=1)
        self.create_subscription(VehicleOdometry, '/fmu/out/vehicle_odometry',
                                 self.on_odom, px4_qos)
        self.create_subscription(TargetState, '/target/state', self.on_target, 10)
        self.create_subscription(CameraInfo, '/camera_info', self.on_info, 10)

        self.pub_ocm = self.create_publisher(
            OffboardControlMode, '/fmu/in/offboard_control_mode', 10)
        self.pub_sp = self.create_publisher(
            TrajectorySetpoint, '/fmu/in/trajectory_setpoint', 10)
        self.pub_cmd = self.create_publisher(
            VehicleCommand, '/fmu/in/vehicle_command', 10)
        # ROS->gz bridged gimbal topics (std_msgs/Float64 -> gz.msgs.Double).
        self.pub_gp = self.create_publisher(Float64, '/gimbal/cmd_pitch', 10)
        self.pub_gy = self.create_publisher(Float64, '/gimbal/cmd_yaw', 10)

        # THE heartbeat. Runs always; never gated by CV.
        self.create_timer(DT, self.loop)
        self.get_logger().info(f'follower up (20 Hz), auto_arm={self.auto_arm}')

    # ================= inputs =================

    def on_info(self, m: CameraInfo):
        self.cam_w, self.cam_h = m.width, m.height
        self.cam_cx, self.cam_cy = m.k[2], m.k[5]

    def on_odom(self, m: VehicleOdometry):
        self.odom = m

    def on_target(self, m: TargetState):
        self.tgt = m
        if m.target_visible:
            self.lost = 0
            self.update_target_world(m)
        else:
            self.lost += 1

    # ================= 20 Hz loop =================

    def loop(self):
        self.tick += 1
        self.t += DT
        self.publish_offboard_mode()          # heartbeat FIRST, every tick
        # ~1.25 s of setpoints streamed first; re-send every 10 s in case the
        # first request is rejected (EKF not ready yet, etc.).
        if self.auto_arm and self.tick >= 25 and (self.tick - 25) % 200 == 0:
            self.engage_offboard_and_arm()
        self.step_state_machine()
        sp = self.compute_setpoint()
        self.pub_sp.publish(sp)
        self.drive_gimbal()

    def publish_offboard_mode(self):
        m = OffboardControlMode()
        m.timestamp = self.now_us()
        m.velocity = True   # we command NED velocity + yawspeed
        m.position = m.acceleration = m.attitude = m.body_rate = False
        self.pub_ocm.publish(m)

    # ================= state machine (design §6) =================

    def step_state_machine(self):
        locked = self.tgt is not None and self.tgt.track_id >= 0
        visible = locked and self.tgt.target_visible
        prev = self.state

        if self.state == 'SEARCH':
            if visible:
                self.state = 'FOLLOW'
        elif self.state == 'FOLLOW':
            if not locked:
                self.state = 'SEARCH'       # operator cleared the lock
            elif self.lost > self.lost_thresh:
                self.state = 'REACQUIRE'
                self.reacq_started = self.t
        elif self.state == 'REACQUIRE':
            if visible:
                self.state = 'FOLLOW'       # perception re-matched (class+pos)
            elif not locked or (self.t - self.reacq_started > self.reacq_timeout):
                self.state = 'HOLD'
        elif self.state == 'HOLD':
            if visible:                     # operator re-selected
                self.state = 'FOLLOW'

        if self.state != prev:
            self.get_logger().info(f'state: {prev} -> {self.state}')
            if self.state == 'FOLLOW':
                self.pid_d.reset(), self.pid_lat.reset()

    # ================= control law (design §5) =================

    def compute_setpoint(self) -> TrajectorySetpoint:
        sp = TrajectorySetpoint()
        sp.timestamp = self.now_us()
        # Velocity control: position must be NaN or PX4 uses it. NED frame.
        sp.position = [math.nan] * 3
        sp.yaw = math.nan

        vx_b = vy_b = 0.0   # body FRD: x forward, y right
        yaw_rate = 0.0      # NED: positive = clockwise (turn right)

        if self.state == 'FOLLOW' and self.tgt is not None and self.tgt.target_visible:
            # Forward: regulate standoff from measured range.
            if math.isfinite(self.tgt.range_m):
                vx_b = self.pid_d.step(self.tgt.range_m - self.d_star, DT)
            # Lateral: small correction from residual horizontal pixel error.
            if self.cam_w:
                e_u = (self.tgt.u - self.cam_cx) / self.cam_w
                # target right of center -> move right (+y in FRD)
                vy_b = self.pid_lat.step(e_u, DT)
            # Heading: yaw body to wash gimbal yaw back to 0.
            # Gimbal yaw + = camera LEFT (FLU); NED yawspeed + = turn RIGHT.
            # So body must turn with OPPOSITE sign of NED convention: negate.
            yaw_rate = clamp(-self.k_body_yaw * self.gimbal_yaw,
                             -self.wr_max, self.wr_max)
        # SEARCH / REACQUIRE / HOLD: zero horizontal velocity (hold position);
        # heartbeat continues so PX4 stays in offboard.

        # Altitude hold in every state. NED: z is DOWN, so altitude = -z.
        vz_ned = 0.0
        if self.odom is not None:
            alt = -float(self.odom.position[2])   # NED z -> altitude (up +)
            climb = self.pid_alt.step(self.alt_hold - alt, DT)  # + = climb
            vz_ned = -climb                        # up + -> NED vz (down +)

        # Rotate body FRD horizontal velocity into NED by vehicle yaw.
        yaw = self.vehicle_yaw_ned()
        vn = vx_b * math.cos(yaw) - vy_b * math.sin(yaw)
        ve = vx_b * math.sin(yaw) + vy_b * math.cos(yaw)

        # Feed-forward: target world velocity (NED) so we don't lag the
        # circling car (design §5). Zero until enough samples.
        if self.state == 'FOLLOW':
            vn += float(self.tgt_vel_ned[0])
            ve += float(self.tgt_vel_ned[1])

        sp.velocity = [clamp(vn, -self.v_max, self.v_max),
                       clamp(ve, -self.v_max, self.v_max),
                       clamp(vz_ned, -2.0, 2.0)]   # UNTUNED vertical limit
        sp.yawspeed = yaw_rate
        return sp

    # ================= gimbal (design §5 inner loop) =================

    def drive_gimbal(self):
        if self.state == 'SEARCH':
            # Slow sinusoidal yaw sweep while waiting for a target. Pitch is
            # reset to the search default too -- otherwise it stays frozen
            # at whatever FOLLOW/REACQUIRE last left it at (e.g. tilted up
            # from a prior lock), which can point the camera above any
            # ground-level target and make re-acquisition impossible.
            self.gimbal_yaw = self.search_amp * math.sin(
                2.0 * math.pi * self.t / self.search_period)
            self.gimbal_pitch = self.search_pitch
        elif self.state in ('FOLLOW',) and self.tgt is not None \
                and self.tgt.target_visible and self.cam_w:
            # Normalized pixel errors; incremental absolute-position command.
            e_pitch = (self.tgt.v - self.cam_cy) / self.cam_h
            e_yaw = (self.tgt.u - self.cam_cx) / self.cam_w
            # Target below center (v>cy) -> pitch camera DOWN (+, gz frame).
            self.gimbal_pitch += self.kp_gp * e_pitch
            # Target right of center (u>cx) -> yaw camera RIGHT = negative
            # gimbal yaw (gz yaw + = left).
            self.gimbal_yaw += -self.kp_gy * e_yaw
        # REACQUIRE/HOLD: freeze gimbal at last-known bearing.

        self.gimbal_pitch = clamp(self.gimbal_pitch,
                                  GIMBAL_PITCH_MIN, GIMBAL_PITCH_MAX)
        self.gimbal_yaw = clamp(self.gimbal_yaw, GIMBAL_YAW_MIN, GIMBAL_YAW_MAX)
        self.pub_gp.publish(Float64(data=self.gimbal_pitch))
        self.pub_gy.publish(Float64(data=self.gimbal_yaw))

    # ================= target world estimate =================

    def update_target_world(self, m: TargetState):
        """Camera-optical target position -> world NED + EMA velocity.

        Chain: optical (x right, y down, z fwd)
          -> camera link FLU (fwd=z_o, left=-x_o, up=-y_o)
          -> body FLU via gimbal Rz(yaw)@Ry(pitch)   [joint order in SDF]
          -> body FRD (x, -y, -z)                    [FLU -> FRD]
          -> world NED via vehicle attitude quaternion + position.
        """
        if self.odom is None or not math.isfinite(m.position_cam.z):
            return
        p_opt = np.array([m.position_cam.x, m.position_cam.y, m.position_cam.z])
        p_frd = optical_to_frd(p_opt, self.gimbal_yaw, self.gimbal_pitch)
        # body FRD -> world NED via odometry attitude (q = [w,x,y,z], FRD->NED)
        tgt_ned = frd_to_ned(p_frd, self.odom.q, self.odom.position)

        now = self.t
        if self.tgt_pos_ned is not None and self.tgt_pos_t is not None:
            dt = now - self.tgt_pos_t
            if dt > 1e-3:
                v = (tgt_ned - self.tgt_pos_ned) / dt
                # EMA filter (design §4): smooths CV jitter for feed-forward.
                self.tgt_vel_ned = (1 - self.ff_alpha) * self.tgt_vel_ned \
                    + self.ff_alpha * v
        self.tgt_pos_ned = tgt_ned
        self.tgt_pos_t = now

    # ================= helpers =================

    def vehicle_yaw_ned(self) -> float:
        """Heading from odometry quaternion. NED yaw: 0 = North, + = CW."""
        if self.odom is None:
            return 0.0
        w, x, y, z = self.odom.q
        return yaw_from_quat(w, x, y, z)

    def now_us(self) -> int:
        return int(self.get_clock().now().nanoseconds / 1000)

    def engage_offboard_and_arm(self):
        self.send_command(VehicleCommand.VEHICLE_CMD_DO_SET_MODE, 1.0, 6.0)
        self.send_command(VehicleCommand.VEHICLE_CMD_COMPONENT_ARM_DISARM, 1.0)
        self.get_logger().info('sent: offboard mode + arm')

    def send_command(self, command: int, p1: float = 0.0, p2: float = 0.0):
        m = VehicleCommand()
        m.timestamp = self.now_us()
        m.command = command
        m.param1, m.param2 = p1, p2
        m.target_system = m.source_system = 1
        m.target_component = m.source_component = 1
        m.from_external = True
        self.pub_cmd.publish(m)


def main(args=None):
    rclpy.init(args=args)
    node = FollowerNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
